### ISSUE TITLE
Library and tests are not working with a Blinkstick pro (v1.1)

### ISSUE THREAD

**Issue by nicolasbauw** [Seltiix/blinkstick-rs#12]
failures:

---- blinkstick::flash_multiple_leds_single_color stdout ----
thread 'blinkstick::flash_multiple_leds_single_color' panicked at src/lib.rs:906:9:
assertion `left == right` failed
  left: [Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }]
 right: [Color { r: 10, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 10, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 10, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 10, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }]

---- blinkstick::get_all_led_colors stdout ----
thread 'blinkstick::get_all_led_colors' panicked at src/lib.rs:884:9:
assertion `left == right` failed
  left: [Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }, Color { r: 0, g: 0, b: 0 }]
 right: [Color { r: 2, g: 2, b: 7 }, Color { r: 2, g: 2, b: 7 }, Color { r: 2, g: 2, b: 7 }, Color { r: 2, g: 2, b: 7 }, Color { r: 2, g: 2, b: 7 }, Color { r: 2, g: 2, b: 7 }, Color { r: 2, g: 2, b: 7 }, Color { r: 2, g: 2, b: 7 }]

---- blinkstick::get_led_color stdout ----
thread 'blinkstick::get_led_color' panicked at src/lib.rs:872:9:
assertion `left == right` failed
  left: Color { r: 0, g: 0, b: 0 }
 right: Color { r: 17, g: 2, b: 3 }

---- blinkstick::pulse_led_color stdout ----
thread 'blinkstick::pulse_led_color' panicked at src/lib.rs:1035:9:
assertion `left == right` failed
  left: Color { r: 0, g: 0, b: 0 }
 right: Color { r: 50, g: 0, b: 0 }

---- blinkstick::transform_led_color stdout ----
thread 'blinkstick::transform_led_color' panicked at src/lib.rs:986:9:
assertion `left == right` failed
  left: Color { r: 0, g: 0, b: 0 }
 right: Color { r: 150, g: 150, b: 150 }

---- blinkstick::transform_multiple_leds_color stdout ----
thread 'blinkstick::transform_multiple_leds_color' panicked at src/lib.rs:1009:9:
assertion `left == right` failed
  left: Color { r: 0, g: 0, b: 0 }
 right: Color { r: 5, g: 5, b: 75 }

failures:
    blinkstick::flash_multiple_leds_single_color
    blinkstick::get_all_led_colors
    blinkstick::get_led_color
    blinkstick::pulse_led_color
    blinkstick::transform_led_color
    blinkstick::transform_multiple_leds_color

**Comment by nicolasbauw** [comment]
No longer needed
